name: ci-check

on:
  push:
    branches: [ main, web-components-step-* ]
  pull_request:
    branches: [ main, web-components-step-* ]

concurrency:
  group: ci-check-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    name: lint
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install dependencies
        run: yarn install
      - name: Build project
        run: yarn build
      - name: Run CI Checks
        run: yarn lint && yarn lint:styles
